import { format } from "date-fns";
import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { PdfAllocationGauge, PdfBarComparisonChart, PdfDonutChart, PdfTrendChart } from "@/features/reports/lib/pdf/charts";
import { pdfPalette } from "@/features/reports/lib/pdf/palette";
import { RecordsPdfTable } from "@/features/reports/lib/pdf/RecordsPdfTable";
import type { ReportInsight, ReportModel } from "@/features/reports/lib/reportModel";
import { formatCurrency, formatPercent } from "@/lib/utils/currency";
import type { Insight, InsightTone } from "@/types";

const styles = StyleSheet.create({
  page: { paddingTop: 70, paddingBottom: 48, paddingHorizontal: 36, fontFamily: "Helvetica", fontSize: 9.5, color: pdfPalette.textPrimary },
  fixedHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 20,
    paddingHorizontal: 36,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: pdfPalette.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  fixedHeaderBrand: { fontSize: 10, fontFamily: "Helvetica-Bold", color: pdfPalette.primary },
  fixedHeaderPeriod: { fontSize: 9, color: pdfPalette.textSecondary },
  fixedFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 36,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: pdfPalette.border,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  fixedFooterText: { fontSize: 8, color: pdfPalette.textTertiary },

  coverTitle: { alignItems: "center", marginBottom: 24 },
  brandName: { fontSize: 22, fontFamily: "Helvetica-Bold", color: pdfPalette.primary, letterSpacing: 0.5 },
  reportKicker: { fontSize: 10, color: pdfPalette.textSecondary, letterSpacing: 2, marginTop: 6 },
  periodTitle: { fontSize: 16, fontFamily: "Helvetica-Bold", color: pdfPalette.textPrimary, marginTop: 10 },
  generatedLine: { fontSize: 8.5, color: pdfPalette.textTertiary, marginTop: 4 },

  sectionTitle: { fontSize: 13, fontFamily: "Helvetica-Bold", color: pdfPalette.textPrimary, marginBottom: 8, marginTop: 20 },
  sectionSubtitle: { fontSize: 9, color: pdfPalette.textSecondary, marginBottom: 10 },

  statGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
  statCard: { width: "31%", padding: 10, borderWidth: 1, borderColor: pdfPalette.border, borderRadius: 6 },
  statLabel: { fontSize: 8, color: pdfPalette.textSecondary },
  statValue: { fontSize: 12, fontFamily: "Helvetica-Bold", color: pdfPalette.textPrimary, marginTop: 3 },

  summaryText: { fontSize: 9.5, lineHeight: 1.5, color: pdfPalette.textSecondary, marginTop: 12 },

  chartCard: { marginTop: 8, padding: 12, borderWidth: 1, borderColor: pdfPalette.border, borderRadius: 6 },
  chartTitle: { fontSize: 9.5, fontFamily: "Helvetica-Bold", color: pdfPalette.textPrimary, marginBottom: 8 },

  insightCard: { padding: 9, borderWidth: 1, borderColor: pdfPalette.border, borderRadius: 6, marginBottom: 6 },
  insightTitle: { fontSize: 9, fontFamily: "Helvetica-Bold", marginBottom: 2 },
  insightExplanation: { fontSize: 8.5, color: pdfPalette.textSecondary, lineHeight: 1.4 },

  allocationRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 6 },
  allocationLabel: { fontSize: 9, color: pdfPalette.textSecondary },
  allocationValue: { fontSize: 9.5, fontFamily: "Helvetica-Bold", color: pdfPalette.textPrimary },
  statusPill: { alignSelf: "flex-start", paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10, fontSize: 8, fontFamily: "Helvetica-Bold", marginTop: 8 },
});

function toneColor(tone: InsightTone): { fg: string; bg: string } {
  if (tone === "positive") return { fg: pdfPalette.income, bg: pdfPalette.incomeLight };
  if (tone === "attention") return { fg: pdfPalette.expense, bg: pdfPalette.expenseLight };
  return { fg: pdfPalette.textSecondary, bg: pdfPalette.background };
}

function FixedHeader({ periodTitle }: { periodTitle: string }) {
  return (
    <View style={styles.fixedHeader} fixed>
      <Text style={styles.fixedHeaderBrand}>myWallet Financial Report</Text>
      <Text style={styles.fixedHeaderPeriod}>{periodTitle}</Text>
    </View>
  );
}

function FixedFooter() {
  return (
    <View style={styles.fixedFooter} fixed>
      <Text style={styles.fixedFooterText}>Generated by myWallet</Text>
      <Text style={styles.fixedFooterText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

// react-pdf's built-in Helvetica only covers WinAnsi — an unrenderable emoji
// (used for extra warmth in the in-app InsightCard) or the "→" comparison
// arrow prints as mojibake, so both are sanitized for the PDF only.
function stripLeadingEmoji(text: string): string {
  return text.replace(/^[\p{Extended_Pictographic}️\s]+/u, "");
}

function sanitizeForPdf(text: string): string {
  return text.replace(/→/g, "->");
}

function InsightCard({ insight }: { insight: Insight }) {
  const { fg, bg } = toneColor(insight.tone);
  return (
    <View style={[styles.insightCard, { backgroundColor: bg, borderColor: bg }]} wrap={false}>
      <Text style={[styles.insightTitle, { color: fg }]}>{stripLeadingEmoji(insight.title)}</Text>
      <Text style={styles.insightExplanation}>{insight.explanation}</Text>
      {insight.comparison && <Text style={[styles.insightExplanation, { marginTop: 2 }]}>{sanitizeForPdf(insight.comparison)}</Text>}
    </View>
  );
}

const SECTION_HEADING: Record<ReportInsight["section"], string> = {
  spending: "Spending Insights",
  income: "Income Insights",
  allocation: "Allocation Insights",
  behavioral: "Ongoing Patterns",
};

export function ReportPdfDocument({ model }: { model: ReportModel }) {
  const { summary } = model;

  const insightsBySection = (["income", "spending", "allocation", "behavioral"] as const)
    .map((section) => ({ section, items: model.insights.filter((i) => i.section === section) }))
    .filter((group) => group.items.length > 0);

  return (
    <Document title={`myWallet Financial Report — ${model.periodTitle}`} author="myWallet">
      {/* Page 1 — cover + executive summary */}
      <Page size="A4" style={styles.page}>
        <FixedHeader periodTitle={model.periodTitle} />
        <FixedFooter />

        <View style={styles.coverTitle}>
          <Text style={styles.brandName}>myWallet</Text>
          <Text style={styles.reportKicker}>FINANCIAL REPORT</Text>
          <Text style={styles.periodTitle}>{model.periodTitle}</Text>
          <Text style={styles.generatedLine}>Generated {format(model.generatedAt, "MMMM d, yyyy")}</Text>
        </View>

        {model.isEmpty ? (
          <View style={{ marginTop: 40, alignItems: "center" }}>
            <Text style={{ fontSize: 11, color: pdfPalette.textSecondary }}>No financial activity recorded for this period.</Text>
            <Text style={{ fontSize: 9, color: pdfPalette.textTertiary, marginTop: 4 }}>
              Start recording income and expenses to generate a meaningful financial report.
            </Text>
          </View>
        ) : (
          <>
            <Text style={styles.sectionTitle}>Financial Overview</Text>
            <View style={styles.statGrid}>
              <StatBox label="Income" value={formatCurrency(summary.income, model.currency)} color={pdfPalette.income} />
              <StatBox label="Expenses" value={formatCurrency(summary.expenses, model.currency)} color={pdfPalette.expense} />
              <StatBox label="Net Balance" value={formatCurrency(summary.netBalance, model.currency)} color={pdfPalette.textPrimary} />
              <StatBox label="Savings" value={formatCurrency(summary.savings, model.currency)} color={pdfPalette.savings} />
              <StatBox label="Investments" value={formatCurrency(summary.investment, model.currency)} color={pdfPalette.investment} />
              <StatBox
                label="Allocation Rate"
                value={summary.allocationRate === null ? "—" : formatPercent(summary.allocationRate, 1)}
                color={pdfPalette.primary}
              />
            </View>

            <Text style={styles.summaryText}>{summary.executiveSummaryText}</Text>

            <View style={styles.chartCard}>
              <Text style={styles.chartTitle}>Income vs Expenses</Text>
              <PdfBarComparisonChart income={summary.income} expenses={summary.expenses} currency={model.currency} />
            </View>
          </>
        )}
      </Page>

      {!model.isEmpty && (
        <>
          {/* Page 2 — Income */}
          <Page size="A4" style={styles.page}>
            <FixedHeader periodTitle={model.periodTitle} />
            <FixedFooter />
            <Text style={styles.sectionTitle}>Income Analysis</Text>
            <Text style={styles.sectionSubtitle}>
              {formatCurrency(model.income.total, model.currency)} recorded across {model.income.count}{" "}
              {model.income.count === 1 ? "record" : "records"}
              {model.income.trendPercent !== 0 ? ` · ${model.income.trendPercent > 0 ? "up" : "down"} ${formatPercent(Math.abs(model.income.trendPercent), 0)} vs. previous period` : ""}
            </Text>
            <RecordsPdfTable
              rows={model.income.records}
              currency={model.currency}
              accentColor={pdfPalette.income}
              emptyLabel="No income recorded for this period."
              labelHeader="Source"
            />
          </Page>

          {/* Page 3 — Expenses */}
          <Page size="A4" style={styles.page}>
            <FixedHeader periodTitle={model.periodTitle} />
            <FixedFooter />
            <Text style={styles.sectionTitle}>Expense Analysis</Text>
            <Text style={styles.sectionSubtitle}>
              {formatCurrency(model.expense.total, model.currency)} spent across {model.expense.count}{" "}
              {model.expense.count === 1 ? "record" : "records"}
              {model.expense.largestCategory ? ` · Largest category: ${model.expense.largestCategory.name}` : ""}
            </Text>

            {model.expense.distribution.length > 0 && (
              <View style={styles.chartCard} wrap={false}>
                <Text style={styles.chartTitle}>Expense Distribution by Category</Text>
                <PdfDonutChart
                  data={model.expense.distribution.map((d, i) => ({
                    name: d.name,
                    amount: d.amount,
                    color: pdfPalette.chartSeries[i % pdfPalette.chartSeries.length],
                  }))}
                  currency={model.currency}
                />
              </View>
            )}

            <RecordsPdfTable
              rows={model.expense.records}
              currency={model.currency}
              accentColor={pdfPalette.expense}
              emptyLabel="No expenses recorded for this period."
              labelHeader="Category"
            />
          </Page>

          {/* Page 4 — Savings & Investment + Insights */}
          <Page size="A4" style={styles.page}>
            <FixedHeader periodTitle={model.periodTitle} />
            <FixedFooter />
            <Text style={styles.sectionTitle}>Savings & Investment</Text>

            <View style={styles.chartCard} wrap={false}>
              <View style={styles.allocationRow}>
                <Text style={styles.allocationLabel}>Savings</Text>
                <Text style={[styles.allocationValue, { color: pdfPalette.savings }]}>{formatCurrency(model.savingsInvestment.savings, model.currency)}</Text>
              </View>
              <View style={styles.allocationRow}>
                <Text style={styles.allocationLabel}>Investments</Text>
                <Text style={[styles.allocationValue, { color: pdfPalette.investment }]}>{formatCurrency(model.savingsInvestment.investment, model.currency)}</Text>
              </View>
              <View style={styles.allocationRow}>
                <Text style={styles.allocationLabel}>Total Allocation</Text>
                <Text style={styles.allocationValue}>{formatCurrency(model.savingsInvestment.totalAllocation, model.currency)}</Text>
              </View>
              <View style={styles.allocationRow}>
                <Text style={styles.allocationLabel}>Recorded Income</Text>
                <Text style={styles.allocationValue}>{formatCurrency(model.savingsInvestment.income, model.currency)}</Text>
              </View>
              <View style={styles.allocationRow}>
                <Text style={styles.allocationLabel}>Allocation Rate vs. {formatPercent(model.savingsInvestment.target, 0)} target</Text>
                <Text style={styles.allocationValue}>{model.savingsInvestment.rate === null ? "—" : formatPercent(model.savingsInvestment.rate, 1)}</Text>
              </View>

              {model.savingsInvestment.rate !== null && (
                <View style={{ marginTop: 8 }}>
                  <PdfAllocationGauge rate={model.savingsInvestment.rate} target={model.savingsInvestment.target} />
                </View>
              )}

              {model.savingsInvestment.band && (
                <Text
                  style={[
                    styles.statusPill,
                    {
                      color: model.savingsInvestment.band === "exceeded" || model.savingsInvestment.band === "reached" ? pdfPalette.income : pdfPalette.savings,
                      backgroundColor: model.savingsInvestment.band === "exceeded" || model.savingsInvestment.band === "reached" ? pdfPalette.incomeLight : pdfPalette.savingsLight,
                    },
                  ]}
                >
                  {model.savingsInvestment.statusLabel}
                </Text>
              )}

              <Text style={styles.summaryText}>{model.savingsInvestment.message}</Text>
              <Text style={[styles.summaryText, { fontSize: 8, color: pdfPalette.textTertiary, marginTop: 6 }]}>
                Allocation Rate = (Savings + Investments) ÷ Income × 100. Allocation is tracked separately from expenses and never
                counted toward Total Expenses.
              </Text>
            </View>

            <RecordsPdfTable
              rows={model.savingsInvestment.records}
              currency={model.currency}
              accentColor={pdfPalette.savings}
              emptyLabel="No savings or investment activity recorded for this period."
              labelHeader="Type"
            />

            {model.charts.trend.length > 1 && (
              <View style={styles.chartCard} wrap={false}>
                <Text style={styles.chartTitle}>Spending Trend</Text>
                <PdfTrendChart points={model.charts.trend} currency={model.currency} />
              </View>
            )}

            {insightsBySection.length > 0 && (
              <>
                <Text style={styles.sectionTitle}>Financial Insights</Text>
                {insightsBySection.map((group) => (
                  <View key={group.section} style={{ marginBottom: 10 }} wrap={false}>
                    <Text style={{ fontSize: 9.5, fontFamily: "Helvetica-Bold", color: pdfPalette.textSecondary, marginBottom: 6 }}>
                      {SECTION_HEADING[group.section]}
                    </Text>
                    {group.items.map((item) => (
                      <InsightCard key={item.insight.id} insight={item.insight} />
                    ))}
                  </View>
                ))}
              </>
            )}
          </Page>
        </>
      )}
    </Document>
  );
}

function StatBox({ label, value, color }: { label: string; value: string; color: string }) {
  return (
    <View style={styles.statCard}>
      <Text style={styles.statLabel}>{label}</Text>
      <Text style={[styles.statValue, { color }]}>{value}</Text>
    </View>
  );
}
