import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { BusinessReportModel } from "@/features/business/lib/businessReportModel";
import { StatementPdfTable, TrialBalancePdfTable } from "@/features/business/lib/pdf/StatementPdfTable";
import { pdfPalette } from "@/features/reports/lib/pdf/palette";
import { formatCurrency } from "@/lib/utils/currency";

const styles = StyleSheet.create({
  page: { paddingTop: 70, paddingBottom: 48, paddingHorizontal: 36, fontFamily: "Helvetica", fontSize: 9.5, color: pdfPalette.textPrimary },
  fixedHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 20,
    paddingHorizontal: 36,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: pdfPalette.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  fixedHeaderBrand: { fontSize: 10, fontFamily: "Helvetica-Bold", color: pdfPalette.primary },
  fixedHeaderPeriod: { fontSize: 9, color: pdfPalette.textSecondary },
  fixedFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 36,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: pdfPalette.border,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  fixedFooterText: { fontSize: 8, color: pdfPalette.textTertiary },

  coverTitle: { alignItems: "center", marginBottom: 24 },
  brandName: { fontSize: 22, fontFamily: "Helvetica-Bold", color: pdfPalette.primary, letterSpacing: 0.5 },
  reportKicker: { fontSize: 10, color: pdfPalette.textSecondary, letterSpacing: 2, marginTop: 6 },
  periodTitle: { fontSize: 16, fontFamily: "Helvetica-Bold", color: pdfPalette.textPrimary, marginTop: 10 },
  generatedLine: { fontSize: 8.5, color: pdfPalette.textTertiary, marginTop: 4 },

  sectionTitle: { fontSize: 13, fontFamily: "Helvetica-Bold", color: pdfPalette.textPrimary, marginBottom: 4, marginTop: 20 },
  sectionSubtitle: { fontSize: 9, color: pdfPalette.textSecondary, marginBottom: 4 },
  netLine: { flexDirection: "row", justifyContent: "space-between", marginTop: 10, paddingTop: 8, borderTopWidth: 1, borderTopColor: pdfPalette.border },
  netLabel: { fontSize: 11, fontFamily: "Helvetica-Bold" },
  netValue: { fontSize: 11, fontFamily: "Helvetica-Bold" },
});

export function BusinessReportPdfDocument({ model }: { model: BusinessReportModel }) {
  const { incomeStatement: is, balanceSheet: bs, cashFlow: cf, trialBalance: tb } = model;

  return (
    <Document title={`${model.businessName} Financial Report — ${model.periodTitle}`} author="myWallet">
      <Page size="A4" style={styles.page}>
        <View style={styles.fixedHeader} fixed>
          <Text style={styles.fixedHeaderBrand}>myWallet Business</Text>
          <Text style={styles.fixedHeaderPeriod}>{model.periodTitle}</Text>
        </View>
        <View style={styles.fixedFooter} fixed>
          <Text style={styles.fixedFooterText}>Generated by myWallet</Text>
          <Text style={styles.fixedFooterText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>

        <View style={styles.coverTitle}>
          <Text style={styles.brandName}>{model.businessName}</Text>
          <Text style={styles.reportKicker}>FINANCIAL REPORT</Text>
          <Text style={styles.periodTitle}>{model.periodTitle}</Text>
          <Text style={styles.generatedLine}>
            Generated {model.generatedAt.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
          </Text>
        </View>

        {model.isEmpty ? (
          <View style={{ marginTop: 40, alignItems: "center" }}>
            <Text style={{ fontSize: 11, color: pdfPalette.textSecondary }}>No financial activity recorded yet.</Text>
          </View>
        ) : (
          <>
            <Text style={styles.sectionTitle} minPresenceAhead={60}>Income Statement</Text>
            <Text style={styles.sectionSubtitle}>{model.periodTitle}</Text>
            <StatementPdfTable
              rows={is.revenueRows.map((r) => ({ label: r.name, amount: r.amount }))}
              total={is.totalRevenue}
              totalLabel="Total Revenue"
              currency={model.currency}
              emptyLabel="No revenue recorded for this period."
            />
            <View style={{ marginTop: 8 }}>
              <StatementPdfTable
                rows={is.expenseRows.map((r) => ({ label: r.name, amount: r.amount }))}
                total={is.totalExpense}
                totalLabel="Total Expenses"
                currency={model.currency}
                emptyLabel="No expenses recorded for this period."
              />
            </View>
            <View style={styles.netLine}>
              <Text style={[styles.netLabel, { color: is.netProfit >= 0 ? pdfPalette.income : pdfPalette.expense }]}>
                Net {is.netProfit >= 0 ? "Profit" : "Loss"}
              </Text>
              <Text style={[styles.netValue, { color: is.netProfit >= 0 ? pdfPalette.income : pdfPalette.expense }]}>
                {formatCurrency(Math.abs(is.netProfit), model.currency)}
              </Text>
            </View>

            <Text style={styles.sectionTitle} minPresenceAhead={60}>Balance Sheet</Text>
            <Text style={styles.sectionSubtitle}>As of {model.dateTo}</Text>
            <StatementPdfTable
              rows={bs.assetRows.map((r) => ({ label: r.name, amount: r.amount }))}
              total={bs.totalAssets}
              totalLabel="Total Assets"
              currency={model.currency}
              emptyLabel="No assets recorded."
            />
            <View style={{ marginTop: 8 }}>
              <StatementPdfTable
                rows={bs.liabilityRows.map((r) => ({ label: r.name, amount: r.amount }))}
                total={bs.totalLiabilities}
                totalLabel="Total Liabilities"
                currency={model.currency}
                emptyLabel="No liabilities recorded."
              />
            </View>
            <View style={{ marginTop: 8 }}>
              <StatementPdfTable
                rows={[...bs.equityRows.map((r) => ({ label: r.name, amount: r.amount })), { label: "Net Income (Current)", amount: bs.netIncomeToDate }]}
                total={bs.totalEquity}
                totalLabel="Total Equity"
                currency={model.currency}
                emptyLabel="No equity recorded."
              />
            </View>

            <Text style={styles.sectionTitle} minPresenceAhead={60}>Statement of Cash Flows</Text>
            <Text style={styles.sectionSubtitle}>{model.periodTitle}</Text>
            <StatementPdfTable
              rows={[
                { label: "Operating Activities", amount: cf.operating },
                { label: "Investing Activities", amount: cf.investing },
                { label: "Financing Activities", amount: cf.financing },
                { label: "Opening Cash Balance", amount: cf.openingCash },
              ]}
              total={cf.closingCash}
              totalLabel="Closing Cash Balance"
              currency={model.currency}
              emptyLabel="No cash activity recorded."
            />

            <Text style={styles.sectionTitle} minPresenceAhead={60}>Trial Balance</Text>
            <Text style={styles.sectionSubtitle}>As of {model.dateTo}</Text>
            <TrialBalancePdfTable rows={tb.rows} totalDebit={tb.totalDebit} totalCredit={tb.totalCredit} currency={model.currency} />
          </>
        )}
      </Page>
    </Document>
  );
}
